// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtnnkybxjewgzadcahzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0bm5reWJ4amV3Z3phZGNhaHpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2MTE0MzksImV4cCI6MjA1NjE4NzQzOX0.ZKZ6Rt9jsbiWNQn65z6YSgwiFm8nJH-s7kMnoUNL7LQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);